---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apresentacao-teste
  namespace: apresentacao
  labels:
    app: apresentacao-teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apresentacao-teste
  template:
    metadata:
      labels:
        app: apresentacao-teste
    spec:
      containers:
      - name: apresentacao-teste
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: MESSAGE
          valueFrom:
            secretKeyRef:
              name: teste-secret-app
              key: sample-secret
        #- name: ADMIN_USER
        #  valueFrom:
        #    secretKeyRef:
        #      key: sample-secret
        #      name: teste-secret-app

