apiVersion: v1
kind: Secret
metadata:
  name: teste-secret-app
  namespace: apresentacao
  annotations:
    avp.kubernetes.io/path: prod/secret
    avp.kubernetes.io/secret-version: "AWSCURRENT"
#stringData:
data:
  sample-secret: <string-connection>
type: Opaque
